### ISSUE TITLE
Dropdown error “module.event.keydown()”

### ISSUE THREAD

**Issue by thiagoaag** [Semantic-Org/UI-Dropdown#7]
I'm following the examples of Dropdown here: http://semantic-ui.com/modules/dropdown.html#/usage. But I catch an error when try navigate on select options with keyboard arrows.

```
<select name="gender" class="ui dropdown" id="select">
  <option value="">Gender</option>
  <option value="male">Male</option>
  <option value="female">Female</option>
</select>

$(document).ready(function () {
    $('#select').dropdown();
});
```

Firefox console output:
```
TypeError: $selectedItem.siblings(...).andSelf is not a function
$.fn.dropdown/</module.event.keydown()                                                semantic.js:5269
o.event.dispatch()                                                                                         jquery.min.js:3
o.event.add/r.handle()                                                                                  jquery.min.js:3
```

**Comment by adnanshussain** [comment]
I'm getting the same problem.

Chrome console 
![image](https://cloud.githubusercontent.com/assets/562248/16109181/9b0b8744-33b8-11e6-97b7-f4eb3d0e3c89.png)

**Comment by adnanshussain** [comment]
Ok found the problem. 

it's working fine with jQuery 2.1.4

It gives this error if I use jQuery >= v3

This is due to the fact that the andSelf() method has been deprecated.

**Comment by thiagoaag** [comment]
Ok @adnanshussain!
Thanks for your response
